version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@microsoft/api-extractor"
    versions:
    - 7.13.0
    - 7.13.1
    - 7.13.2
    - 7.13.4
  - dependency-name: "@microsoft/api-documenter"
    versions:
    - 7.12.12
    - 7.12.14
    - 7.12.15
    - 7.12.16
    - 7.12.20
    - 7.12.6
    - 7.12.7
    - 7.12.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: puppeteer-extra-plugin-stealth
    versions:
    - 2.6.6
    - 2.6.7
    - 2.7.4
    - 2.7.5
    - 2.7.6
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.1
